# Generated by Django 5.2.10 on 2026-01-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_additionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='batch_year',
            field=models.IntegerField(blank=True, choices=[(2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034)], null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='upazilla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
