# Generated by Django 5.2.10 on 2026-01-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_additionalinfo_batch_year_additionalinfo_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
